### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by mkreisl** [kodi-pvr/pvr.mediaportal.tvserver#125]
```
/home/xbian/xbian-package-xbmc/build/rpi4-matrix/working/cmake/addons/build/pvr.mediaportal.tvserver/src/GUIDialogRecordSettings.cpp:15:10: fatal error: kodi/ActionIDs.h: No such file or directory
 #include <kodi/ActionIDs.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
```

I'm sorry to have to say this, but the constant senseless changes are an absolute horror

**Comment by AlwinEsch** [comment]
These changes already have a background (Kodi page) and since Kodi Matrix is still in alpha, things like that happen more often.

The reason why such changes are currently so common is related to the improvement of the add-on interface to allow for other languages and to have it more secure against hidden errors (correct C++ -> C -> C++ API).

When Kodi Matrix gets its final release, things like that won't be touched in it anymore.

Due to the delayed construction of Kodi (Ubuntu launchpad) addon adjustments always have to wait up to 24 hours before they come.

**Comment by mkreisl** [comment]
Yeah, but I can't find a PR solving this issue

**Comment by mkreisl** [comment]
Yeah, I know. But I have nothing to do with Ubuntu and I can't find a PR solving this issue

**Comment by mkreisl** [comment]
Yeah, I know. But I have nothing to do with Ubuntu and I can't find a PR solving this issue

**Comment by mkreisl** [comment]
Yeah, I know. But I have nothing to do with Ubuntu and I can't find a PR solving this issue

**Comment by mkreisl** [comment]
Yeah, I know. But I have nothing to do with Ubuntu and I can't find a PR solving this issue

**Comment by mkreisl** [comment]
Yeah, I know. But I have nothing to do with Ubuntu and I can't find a PR solving this issue

**Comment by mkreisl** [comment]
Yeah, I know. But I have nothing to do with Ubuntu and I can't find a PR solving this issue

**Comment by mkreisl** [comment]
Yeah, I know. But I have nothing to do with Ubuntu and I can't find a PR solving this issue

**Comment by mkreisl** [comment]
Yeah, I know. But I have nothing to do with Ubuntu and I can't find a PR solving this issue

**Comment by mkreisl** [comment]
Yeah, I know. But I have nothing to do with Ubuntu and I can't find a PR solving this issue

**Comment by mkreisl** [comment]
Yeah, I know. But I have nothing to do with Ubuntu and I can't find a PR solving this issue

**Comment by mkreisl** [comment]
Yeah, I know. But I have nothing to do with Ubuntu and I can't find a PR solving this issue

**Comment by mkreisl** [comment]
Yeah, I know. But I have nothing to do with Ubuntu and I can't find a PR solving this issue

**Comment by mkreisl** [comment]
Yeah, I know. But I have nothing to do with Ubuntu and I can't find a PR solving this issue

**Comment by mkreisl** [comment]
Yeah, I know. But I have nothing to do with Ubuntu and I can't find a PR solving this issue

**Comment by mkreisl** [comment]
Yeah, I know. But I have nothing to do with Ubuntu and I can't find a PR solving this issue

**Comment by mkreisl** [comment]
Yeah, I know. But I have nothing to do with Ubuntu and I can't find a PR solving this issue

**Comment by mkreisl** [comment]
Yeah, I know. But I have nothing to do with Ubuntu and I can't find a PR solving this issue

**Comment by mkreisl** [comment]
Yeah, I know. But I have nothing to do with Ubuntu and I can't find a PR solving this issue

**Comment by mkreisl** [comment]
Yeah, I know. But I have nothing to do with Ubuntu and I can't find a PR solving this issue

**Comment by mkreisl** [comment]
Yeah, I know. But I have nothing to do with Ubuntu and I can't find a PR solving this issue

**Comment by mkreisl** [comment]
Yeah, I know. But I have nothing to do with Ubuntu and I can't find a PR solving this issue

**Comment by mkreisl** [comment]
Yeah, I know. But I have nothing to do with Ubuntu and I can't find a PR solving this issue

**Comment by mkreisl** [comment]
Yeah, I know. But I have nothing to do with Ubuntu and I can't find a PR solving this issue

**Comment by mkreisl** [comment]
Yeah, I know. But I have nothing to do with Ubuntu and I can't find a PR solving this issue

**Comment by mkreisl** [comment]
Yeah, I know. But I have nothing to do with Ubuntu and I can't find a PR solving this issue

**Comment by mkreisl** [comment]
Yeah, I know. But I have nothing to do with Ubuntu and I can't find a PR solving this issue

**Comment by mkreisl** [comment]
Yeah, I know. But I have nothing to do with Ubuntu and I can't find a PR solving this issue

**Comment by mkreisl** [comment]
Yeah, I know. But I have nothing to do with Ubuntu and I can't find a PR solving this issue

**Comment by mkreisl** [comment]
Yeah, I know. But I have nothing to do with Ubuntu and I can't find a PR solving this issue

**Comment by mkreisl** [comment]
Yeah, I know. But I have nothing to do with Ubuntu and I can't find a PR solving this issue

**Comment by mkreisl** [comment]
Yeah, I know. But I have nothing to do with Ubuntu and I can't find a PR solving this issue

**Comment by mkreisl** [comment]
Yeah, I know. But I have nothing to do with Ubuntu and I can't find a PR solving this issue

**Comment by AlwinEsch** [comment]
If you don't finish flooding comments you will be blocked at the repo!

The associated change comes in a few minutes to the request that this header was used went under.

**Comment by mkreisl** [comment]
Don't panic, something went wrong with my browser. Probably the browser is as angry as I am

Next build error for **vfs.rar**. Btw, what sense do PR's make if they are not committed or if they are only committed after a long delay, see vfs.rar repo?

**Comment by margro** [comment]
Matrix is released, so I guess we can close this.
