### ISSUE TITLE
Omega 21.0.1 - LiveTV and RecordedTV Fail TSReader

### ISSUE THREAD

**Issue by Leetxjd** [kodi-pvr/pvr.mediaportal.tvserver#208]
My previously working use of this add-on, since Omega, is no longer working properly on my Sony AndroidTV.

Playback setting that used to work - TSReader with NO RTSP.

Under Omega - that setting will not work.  To get LiveTV I must select RTSP. However, then I can't watch RecordedTV as Kodi will either not play or crash - plus I can't advance in the recorded video.

If I use TSReader without RTSP (RSTP OFF) in Omega, I can't watch LiveTV, but I can watch RecordedTV.  

There is no way for me to use a single setting and have both LiveTV and RecordedTV playback.  

Just as an FYI - I have another TV still on Nexus - and it works fine.

I have a logfile attached.

[kodi RTSPOFF LiveTVFails RecordedPlays .log](https://github.com/kodi-pvr/pvr.mediaportal.tvserver/files/15477885/kodi.RTSPOFF.LiveTVFails.RecordedPlays.log)

**Comment by phunkyfish** [comment]
Can you install one of these addon builds and see does it make a difference?

https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.mediaportal.tvserver/detail/PR-207/5/artifacts

**Comment by phunkyfish** [comment]
Are you using MP1 or MP2?

**Comment by Leetxjd** [comment]
Sorry for the delay in replying (work got in the way).

I am using MP1.  I will install the add-on builds you have directed me to in the post above and let you know.

-LeeTXJD

**Comment by Leetxjd** [comment]
I used the install build from above - and I still cannot get a LiveTV stream.  I have attached my log.

[kodi AFTER Addon Update.log](https://github.com/user-attachments/files/15526088/kodi.AFTER.Addon.Update.log)

**Comment by phunkyfish** [comment]
Have you tried MP2?

**Comment by Leetxjd** [comment]
No, I use a Hauppauge HD-PVR and to my recollection there are incompatibilities with MP2 (its been more than a few years since I set this all up).  
Your question made me visit the MP website and I updated my MP to the latest version.  An interesting anomaly revealed itself. 

I was able to use Kodi normally - watch TV and watch recordings.  
On exiting Kodi and reentering - it then failed.

I have attached the logs in case it shows something.

[kodi fails.log](https://github.com/user-attachments/files/15810325/kodi.fails.log)
[kodi works.log](https://github.com/user-attachments/files/15810326/kodi.works.log)

**Comment by phunkyfish** [comment]
Interesting. If you switch off your tv and turn it on again does it work the first time you run Kodi?

also, did you try with the build I supplied above?

here’s a fresh build in case the previous one has expired: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.mediaportal.tvserver/detail/PR-207/7/artifacts

**Comment by Leetxjd** [comment]
No - the working condition occurs when I change the add-on settings turning RSTP to off.  Kodi works as it did before.  However, when I exit and then reload Kodi I get the fail condition.

I did try 21.0.3, but I will download and reinstall - just in case.

**Comment by phunkyfish** [comment]
So every time you turn RTSP to off it works?

**Comment by Leetxjd** [comment]
No, I was very unclear.  Here is how for a single instance (start of Kodi through to exiting Kodi) everything will work under Omega:

1. Start Kodi.
2. MediaPortal PVR client playback is previously already set to RTSP streaming off under playback.
3. Play a recorded TV show.  It works no problem. LiveTV does NOT work.
4. Change MediaPortal PVR client playback to RTSP streaming ON.
5. LiveTV works AND recorded TV will also play.  (Note:  I must do step 3 for this to work - If I don't do step 3 before changing settings - playing RecordedTV will crash Kodi).
6. As long as I don't exit Kodi - everything is fine.
7. Exit Kodi.
8. Return to Kodi.
9. LiveTV works, but RecordedTV will crash Kodi.

I thought perhaps this might be a SonyTV android issue.  I hooked up a NVIDIA Shield to double check.  Under Nexus with RTSP off - no problems on the Shield.  Under Omega using my Shield, I can confirm with RTSP off there no LiveTV - and if I use RTSP, RecordedTV crashes Kodi just as under my SonyTVs.  
[kodi.log](https://github.com/user-attachments/files/15845013/kodi.log)

PS - I need to buy you a coffee or beer for looking into this.  If you have a patreon or venmo, I'd like to make a donation.

**Comment by wwwFINKcz** [comment]
the same problem here 
only RTSP is working. And if I pause the show, the stream crashes .... not possible to move back. With the old (non RTSP) version it was much much better. Now can I only switch to RTSP and watch the current show(stream) position.
(win10 with mediaportal2 as server and kodi client on another pc with kodi mediaportal plugin)

**Comment by phunkyfish** [comment]
> No, I was very unclear. Here is how for a single instance (start of Kodi through to exiting Kodi) everything will work under Omega:
> 
> 1. Start Kodi.
> 2. MediaPortal PVR client playback is previously already set to RTSP streaming off under playback.
> 3. Play a recorded TV show.  It works no problem. LiveTV does NOT work.
> 4. Change MediaPortal PVR client playback to RTSP streaming ON.
> 5. LiveTV works AND recorded TV will also play.  (Note:  I must do step 3 for this to work - If I don't do step 3 before changing settings - playing RecordedTV will crash Kodi).
> 6. As long as I don't exit Kodi - everything is fine.
> 7. Exit Kodi.
> 8. Return to Kodi.
> 9. LiveTV works, but RecordedTV will crash Kodi.
> 
> I thought perhaps this might be a SonyTV android issue. I hooked up a NVIDIA Shield to double check. Under Nexus with RTSP off - no problems on the Shield. Under Omega using my Shield, I can confirm with RTSP off there no LiveTV - and if I use RTSP, RecordedTV crashes Kodi just as under my SonyTVs. [kodi.log](https://github.com/user-attachments/files/15845013/kodi.log)
> 
> PS - I need to buy you a coffee or beer for looking into this. If you have a patreon or venmo, I'd like to make a donation.

If you’d like to donate something just donate to the kodi foundation. That’ll go towards our next devcon 😉

**Comment by phunkyfish** [comment]
Have you all installed the latest c++ runtime? Just in case this is the issue:

https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by wwwFINKcz** [comment]
> Have you all installed the latest c++ runtime? Just in case this is the issue:
> 
> https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

if you talk about this exe - yes. It is installed on all across my home computers (win11 and win10 with Kodi). The results are the same, it is crashing instantly with RTSP off, with RTSP on I can watch only the current time of the show. [<html><body>

  | https://aka.ms/vs/17/release/vc_redist.x64.exe
-- | --



</body>
</html>

**Comment by Leetxjd** [comment]
> Have you all installed the latest c++ runtime? Just in case this is the issue:
> 
> https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

I will double check, but I think I am up to date.

**Comment by wwwFINKcz** [comment]
confirmed... tried to uninstall KODI 21 and install the KODI 20 and it works INSTANTLY as it should (no RTSP on), timeshift/pause without any slightest issue.

**Comment by Leetxjd** [comment]
I made sure that the runtime was the latest version.  I still am unable to use it with (no RTSP on).

**Comment by Leetxjd** [comment]
Just an update - I have been playing with all sorts of settings and can't get the add-on to work with (no RTSP on).

Also, I took your advice and supported the Kodi Foundation.  I love using KODI with AndroidTV!

**Comment by WindyOldMan** [comment]
If it is any help, I posted a comment and potential code fix for this against the Kodi issue (https://github.com/xbmc/xbmc/issues/24869) including the diffs. Code changes are needed in both Kodi (very minor) itself and the pvt.mediaportal.tvserver addon so I was not sure where to post my comment and potential code fix.

**Comment by phunkyfish** [comment]
The kodi PRs have been merged. Nightlies from Oct 17th will contain the required changes.

test builds of the addon can be used with these nightlies for testing the fix.

Kodi 22 Piers: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.mediaportal.tvserver/detail/PR-215/4/artifacts
Kodi 21 Omega: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.mediaportal.tvserver/detail/PR-216/3/artifacts

**Comment by phunkyfish** [comment]
@Leetxjd  latest nightlies now contain the Kodi change. Can you both use a latest nightly (https://mirrors.kodi.tv/nightlies/) and the add-on testbuilds above to test the changes?

**Comment by phunkyfish** [comment]
Closing this issue as all required fixes are now merged and tested by users.

note that Omega nightlies will need to used until 21.2 is released.m

please reopen if you find different @Leetxjd
