### ISSUE TITLE
Active timers as part of series schedule missing

### ISSUE THREAD

**Issue by puenktchen** [kodi-pvr/pvr.mediaportal.tvserver#45]
@margro  @ksooo 
A timer that is part of a series schedule (timer rule) and that is currently recording
is missing from all screens in Kodi (timers, timer rules, tv guide), so there's no way to cancel an active timer. One time schedules are working as expected.
This happens with Kodi Jarvis 16.1 and Kodi Krypton nightlies,
MediaPortal TVServer 1.15 and TVServer Kodi plugin 1.15.0.134.

**Comment by puenktchen** [comment]
This can be closed.
It seems to be fixed by one of the previous Krypton beta releases.

**Comment by margro** [comment]
Closed on request.
