### ISSUE TITLE
does not compile on android

### ISSUE THREAD

**Issue by ksooo** [kodi-pvr/pvr.mediaportal.tvserver#49]
compilation of master fails on android:

<pre>
/home/jenkins/workspace/Android-ARM/tools/depends/target/binary-addons/arm-linux-androideabi-android-21/build/pvr.mediaportal.tvserver/src/lib/live555/groupsock/GroupsockHelper.cpp:503:21: error: request for member 's_addr' in 'imr.ip_mreq_source::imr_multiaddr', which is of non-class type '__be32 {aka unsigned int}'
   imr.imr_multiaddr.s_addr = groupAddress;
                     ^
[ 64%] Building C object CMakeFiles/pvr.mediaportal.tvserver.dir/src/lib/live555/groupsock/inet.c.o
/home/jenkins/workspace/Android-ARM/tools/depends/target/binary-addons/arm-linux-androideabi-android-21/build/pvr.mediaportal.tvserver/src/lib/live555/groupsock/GroupsockHelper.cpp:504:22: error: request for member 's_addr' in 'imr.ip_mreq_source::imr_sourceaddr', which is of non-class type '__be32 {aka unsigned int}'
   imr.imr_sourceaddr.s_addr = sourceFilterAddr;
                      ^
/home/jenkins/workspace/Android-ARM/tools/depends/target/binary-addons/arm-linux-androideabi-android-21/build/pvr.mediaportal.tvserver/src/lib/live555/groupsock/GroupsockHelper.cpp:505:21: error: request for member 's_addr' in 'imr.ip_mreq_source::imr_interface', which is of non-class type '__be32 {aka unsigned int}'
   imr.imr_interface.s_addr = ReceivingInterfaceAddr;
                     ^
/home/jenkins/workspace/Android-ARM/tools/depends/target/binary-addons/arm-linux-androideabi-android-21/build/pvr.mediaportal.tvserver/src/lib/live555/groupsock/GroupsockHelper.cpp: In function 'Boolean socketLeaveGroupSSM(UsageEnvironment&, int, netAddressBits, netAddressBits)':
/home/jenkins/workspace/Android-ARM/tools/depends/target/binary-addons/arm-linux-androideabi-android-21/build/pvr.mediaportal.tvserver/src/lib/live555/groupsock/GroupsockHelper.cpp:521:21: error: request for member 's_addr' in 'imr.ip_mreq_source::imr_multiaddr', which is of non-class type '__be32 {aka unsigned int}'
   imr.imr_multiaddr.s_addr = groupAddress;
                     ^
/home/jenkins/workspace/Android-ARM/tools/depends/target/binary-addons/arm-linux-androideabi-android-21/build/pvr.mediaportal.tvserver/src/lib/live555/groupsock/GroupsockHelper.cpp:522:22: error: request for member 's_addr' in 'imr.ip_mreq_source::imr_sourceaddr', which is of non-class type '__be32 {aka unsigned int}'
   imr.imr_sourceaddr.s_addr = sourceFilterAddr;
                      ^
/home/jenkins/workspace/Android-ARM/tools/depends/target/binary-addons/arm-linux-androideabi-android-21/build/pvr.mediaportal.tvserver/src/lib/live555/groupsock/GroupsockHelper.cpp:523:21: error: request for member 's_addr' in 'imr.ip_mreq_source::imr_interface', which is of non-class type '__be32 {aka unsigned int}'
   imr.imr_interface.s_addr = ReceivingInterfaceAddr;
</pre>

**Comment by ksooo** [comment]
@koying do you have a clue what could be the problem/fix?

**Comment by margro** [comment]
Hmm, this is code from an external library live555 used for rtsp stream reading. I'm already in the progress of trying to switch to the latest version (current code is from 2008) but somehow, the latest version does not stream at all. MediaPortal itself also never upgraded their live555 copy (probably for a good reason).

What we could do as temporary fix is disable live555 support for Android only.
Which CMake variable can I use to detect an Android build?

**Comment by ksooo** [comment]
@margro people complaining in the forum no longer having the addon on android. maybe you can tell them? => http://forum.kodi.tv/showthread.php?tid=294090&pid=2446393#pid2446393

> What we could do as temporary fix is disable live555 support for Android only.
> Which CMake variable can I use to detect an Android build?

@hudokkow ^^^^

**Comment by margro** [comment]
@ksooo I will respond there. I probably have a proper fix that I can backport from upstream live555.

**Comment by ksooo** [comment]
@margro cool, thanks
