### ISSUE TITLE
Old Recordings did not get deleted automatically

### ISSUE THREAD

**Issue by popy2k14** [kodi-pvr/pvr.mediaportal.tvserver#70]
When you create an timer from guide or an instant recording with mediaportal pvr backend, the default value of lifetime is "MPTV_KEEP_ALWAYS".

This has the effect that old recordings did'nt get deleted from the backend when you have set a disk quota (to delete old recordings).

it would be better to set the Default value to "MPTV_KEEP_UNTIL_SPACE_NEEDED". After a quick test with this Setting old recordings gets deleted by the backend if disk is nearly full.

In the Forum there are users with the same issue and a possible fix is posted here: ​https://forum.kodi.tv/showthread.php?tid=301878&pid=2606063#pid2606063

**Comment by margro** [comment]
This is intentional and not a bug. Automatically deleting old recordings is not what all people expect. Some want to keep old recordings, other don't care.
