### ISSUE TITLE
Kodi Crashes When Trying to View Live Stream or Recorded Show

### ISSUE THREAD

**Issue by elmojo** [kodi-pvr/pvr.mediaportal.tvserver#83]
Whenever I now try to use the Kodi MediaPortal add-on, it Kodi crashes to the "sad face" and and then restarts.  This happens whenever I try to view live TV or view a recorded show.

I can view the recorded shows fine by going through the "file system" and clicking on the *.ts file.  But if I try to view it through the MediaPortal add-on, it crashes.

This issue is reproducible every time on my machine.

Let me know what is needed to help resolve this issue.

**Comment by margro** [comment]
Well, without any details, I cannot fix things. I need at least a Kodi debug log and details like the used Kodi version and the operating system and the version of the MediaPortal TV Server

**Comment by elmojo** [comment]
I will try and post these as soon as I can.  Thanks.

**Comment by margro** [comment]
No feedback. Closing this issue for now. Feel free to reopen if this is still an issue for you.
