### ISSUE TITLE
can't install kodi-pvr-mediaportal-tvserver package as it's missing from PPA index

### ISSUE THREAD

**Issue by ehough** [kodi-pvr/pvr.mediaportal.tvserver#86]
Currently this package can't be installed on Ubuntu. Here's how to reproduce:

```
$ docker run -it --rm ubuntu:bionic
# apt-get update && apt-get -y install software-properties-common
  ...
# add-apt-repository ppa:team-xbmc/ppa && apt-get update
  ...
# apt-get install kodi kodi-pvr-mediaportal-tvserver
  ...
  Some packages could not be installed. This may mean that you have
  requested an impossible situation or if you are using the unstable
  distribution that some required packages have not yet been created
  or been moved out of Incoming.
  The following information may help to resolve the situation:

  The following packages have unmet dependencies:
   kodi-pvr-mediaportal-tvserver : Depends: kodi-api-pvr (= 5.2.1)
  E: Unable to correct problems, you have held broken packages.
```
The package is missing from the [PPA's index](http://ppa.launchpad.net/team-xbmc/ppa/ubuntu/dists/bionic/main/binary-amd64/Packages.gz), but it's present on the [overview page](https://launchpad.net/~team-xbmc/+archive/ubuntu/ppa?field.series_filter=bionic). I'm probably using the wrong terminology but I hope you get the idea.

**Comment by margro** [comment]
Fix for Krypton committed in: https://github.com/kodi-pvr/pvr.mediaportal.tvserver/commit/dca933b52487543952a77a95723394cdc4883f88

**Comment by margro** [comment]
Note that I cannot trigger a rebuild of the PPA packages as I'm not the owner.

**Comment by margro** [comment]
Should be fixed by now.

**Comment by ehough** [comment]
Confirmed it's fixed. Thank you @margro
