### ISSUE TITLE
Constant buffering of live tv under Kodi Leia

### ISSUE THREAD

**Issue by puenktchen** [kodi-pvr/pvr.mediaportal.tvserver#92]
Hi @margro ,
i've already opened a ticket with logs on trac.kodi.tv https://trac.kodi.tv/ticket/17980 but it was closed
because it's addon related. @ksooo mentioned a possible solution could be the proper implementation
of the GetStreamReadChunkSize parameter as a user setting.
Here's his commit for Tvheadend https://github.com/kodi-pvr/pvr.hts/commit/496a8b1ce9315303a3342f23a415c8edc6599297
Can you please have a look?!

**Comment by margro** [comment]
I've implemented the GetStreamReadChunkSize() functions in v3.5.17. Hopefully this reduces the buffering in your case.

**Comment by margro** [comment]
No answer yet. Closing this issue. If the problem still occurs, please create a new issue.
