### ISSUE TITLE
Kodi crashes when installing MPPVR v3.5.9.2 on LE 8.90.006 on RPi 3B+

### ISSUE THREAD

**Issue by sbs20** [kodi-pvr/pvr.mediaportal.tvserver#96]
Apologies if this is double posting. Kodi goes into a crash loop and starts in safe mode when installing the mediaportal plugin. More info [here](https://forum.kodi.tv/showthread.php?tid=337006&pid=2788209#pid2788209). Log file [here](https://paste.kodi.tv/obepipeguj.kodi)

I can boot again by SSHing and removing the plugin from the addon directory.

**Comment by margro** [comment]
Crash should not happen anymore since plugin version v3.5.11. Please reopen if still an issue.
