### ISSUE TITLE
Cannot watch SD recordings, HD ok

### ISSUE THREAD

**Issue by matthiaskind** [kodi-pvr/pvr.mediaportal.tvserver#98]
In Kodi v18, I cannot play recordings of programs that are in SD / MPEG-2 (e.g. RTL or VOX in Germany). HD (720p, e.g. ARD HD) are fine. I only have free tv.
When i click on a SD recording nothing happens. Sometime i see the loading symbol for about 1 ms.
I can play the SD recordings without problems if i create a library of the SMB share of my MediaPortal server an start the .ts files from there.

The behavior is the same on both my test clients.

Logs:
Server MP2 debug log: https://pastebin.com/wD4aEbn4
  SetupTV log: https://pastebin.com/YDZWd4EM
Client2 Kodi debug log: https://pastebin.com/897G3zuX

Time of test: ~ 2018-12-09, 18:02
I first tried two recordings of "hundkatzemaus" (VOX, SD), which didn't start. Then I started "Elefant Tiger & Co." (MDR, HD) successfully.

My setup:
Server:
- MP2 Server 2.2 on Windows 10
- MediaPortal_2_2_pre_TVServerKodi_plugin_rev139
- Shares are created, permissions set to full for "Everyone". Live TV is working fine in SD and HD.

Client1:
- Intel PC with NVIDIA GT 1030
- LibreELEC Generic 8.90.009
- pvr.mediaportal.tvserver-3.5.13-Leia

Client2:
- Raspberry 3B
- LibreELEC RPi2.arm 8.90.009
- pvr.mediaportal.tvserver-3.5.13-Leia

edit: Tested on Kodi 17.6 with PVR AddOn 2.4.19: All recordings are running fine. So this only seems to happen in V18!?

**Comment by scorpionking** [comment]
Sorry, closed unintentionally.

**Comment by margro** [comment]
Should be fixed since v3.5.15. Please reopen if it still an issue.
